; PlatformIO Project Configuration File for Duck Firmware
;
; This is an example platformio.ini for a Duck firmware project
; that includes the QuackPack Template.
;
; Copy this to your Duck firmware project and modify as needed.

[platformio]
description = GPS Quack-Pack
default_envs = prod_heltec_wifi_lora_32_V3

[env]
monitor_speed = 115200
upload_speed = 921600
build_src_filter =
	-<*>
; Dependencies
[esp32_base]
platform = espressif32@6.12.0
framework = arduino
lib_deps =
; uncomment the following line to use the build in main branch, which pulls all dependencies
	symlink://./
	FastLED/FastLED@^3.10.3
	adafruit/Adafruit uBlox@^1.0.0
	mikalhart/TinyGPSPlus@~1.0.2
	adafruit/Adafruit BusIO@^1.17.4

[env:t-beam-sx1262]
extends = esp32_base
board = ttgo-t-beam
build_src_filter =
	${env.build_src_filter}
	+<../examples/BasicDuckFirmware/src/*.cpp>
lib_deps =
	${esp32_base.lib_deps}
build_flags =
	-D CDP_LOG_DEBUG
;-D TINYFORMAT_USE_VARIADIC_TEMPLATES
	-D ARDUINO_T_BEAM_SX1262
	-std=gnu++2a
build_unflags =
	-std=gnu++11

[env:t-beam-sx1276]
extends = esp32_base
board = ttgo-lora32-v1
build_src_filter =
	${env.build_src_filter}
	+<../examples/BasicDuckFirmware/src/*.cpp>
lib_deps =
	${esp32_base.lib_deps}
build_flags =
	-DXPOWERS_CHIP_AXP192
	-std=gnu++2a
build_unflags =
	-std=gnu++11

[env:release_cdp]
extends = esp32_base
lib_deps =
	https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/archive/refs/tags/5.0.0.zip
	https://github.com/Project-Owl/QuackPack-Base
	FastLED/FastLED@^3.10.3
	adafruit/Adafruit uBlox@^1.0.0
	mikalhart/TinyGPSPlus@~1.0.2
	adafruit/Adafruit BusIO@^1.17.4
[env:prod_heltec_wifi_lora_32_V2]
extends = env:release_cdp
board = heltec_wifi_lora_32_V2

[env:prod_heltec_wifi_lora_32_V3]
extends = env:release_cdp
board = heltec_wifi_lora_32_V3

[env:prod_lilygo_t_beam_sx1262]
extends = env:release_cdp
board = ttgo-t-beam

[env:prod_lilygo_t_beam_supreme_sx1262]
extends = env:release_cdp
board = esp32-s3-devkitc-1
build_flags =
	${env:release_cdp.build_flags}
	-DARDUINO_LILYGO_T_BEAM_SUPREME
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
monitor_speed = 115200

[env:prod_lilygo_t_beam_sx1276]
extends = env:release_cdp
board = ttgo-lora32-v1

[env:prod_ttgo_lora32_v1_3]
extends = env:release_cdp
board = ttgo-lora32-v1
build_flags =
	${env:esp32_base.build_flags}
	-DTTGO_1_3