; PlatformIO Project Configuration File for Duck Firmware
;
; This is an example platformio.ini for a Duck firmware project
; that includes the QuackPack Template.
;
; Copy this to your Duck firmware project and modify as needed.
[platformio]
description = GPS Quack-Pack
lib_dir = .
src_dir = ./examples/BasicDuckFirmware
default_envs = prod_heltec_wifi_lora_32_V3
; build_src_filter =
;     -<*>

[esp32_base]
monitor_speed = 115200
upload_speed = 921600
monitor_filters = time
lib_compat_mode = strict
lib_ldf_mode = chain
build_flags = 
	-std=gnu++2a
	-Wno-inconsistent-missing-override
	-Wno-missing-field-initializers
	-Wno-format
	-I ./src
build_unflags = 
	-std=gnu++11
platform = espressif32
board = esp32dev
framework = arduino

[env:release_cdp]
extends = esp32_base
lib_deps = 
	https://github.com/faradaym/ClusterDuck-Protocol.git#signal-health
	https://github.com/Project-Owl/QuackPack-Base
    FastLED/FastLED@^3.10.3
    adafruit/Adafruit uBlox@^1.0.0
    mikalhart/TinyGPSPlus@~1.0.2
    adafruit/Adafruit BusIO@^1.17.4
[env:prod_heltec_wifi_lora_32_V2]
extends = env:release_cdp
board = heltec_wifi_lora_32_V2

[env:prod_heltec_wifi_lora_32_V3]
extends = env:release_cdp
board = heltec_wifi_lora_32_V3

[env:prod_lilygo_t_beam_sx1262]
extends = env:release_cdp
board = ttgo-t-beam

[env:prod_lilygo_t_beam_supreme_sx1262]
extends = env:release_cdp
board = esp32-s3-devkitc-1
build_flags = 
	${env:release_cdp.build_flags}
	-DARDUINO_LILYGO_T_BEAM_SUPREME
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
monitor_speed = 115200

[env:prod_lilygo_t_beam_sx1276]
extends = env:release_cdp
board = ttgo-lora32-v1

[env:prod_ttgo_lora32_v1_3]
extends = env:release_cdp
board = ttgo-lora32-v1
build_flags = 
	${env:esp32_base.build_flags}
	-DTTGO_1_3
; build_src_filter =
;     ${env.build_src_filter}
;     +<../examples/BasicDuckFirmware/src/*.cpp>
